name: Build the .unitypackage

on:
  workflow_call:
    inputs:
      build-method:
        description: "The build script in Unity."
        default: "Build.CreateAllEmbeddedUnityPackages"
        required: true
        type: string
      bare-repository:
        description: "True if the repository only contains the package hierarchy"
        default: true
        required: true
        type: boolean

jobs:
  push-to-aws:
    name: Build .unitypackage and push to artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout unity empty project
        if: ${{ inputs.bare-repository }}
        uses: actions/checkout@v3
        with:
          repository: homapf/unity-empty-project

      - name: Checkout bare package
        if: ${{ inputs.bare-repository }}
        uses: actions/checkout@v3
        with:
          path: Packages/${{ github.event.repository.name }}

      - name: Checkout repo package
        if: ${{ !inputs.bare-repository }}
        uses: actions/checkout@v3

      - uses: actions/cache@v2
        with:
          path: Library
          key: Library

      - name: Build .unitypackage for package
        uses: game-ci/unity-builder@v2
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          buildMethod: ${{ inputs.build-method }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          allowDirtyBuild: true
          versioning: None

      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: Build/
