name: Create .unitypackage in release

on:
  workflow_call:

jobs:
  push-to-github:
    name: Create project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: Package
          path: Build/

      - name: Upload .unitypackage to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: Build/*/*/*.unitypackage
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
